### ISSUE TITLE
Photo booth start page

### ISSUE THREAD

**Issue by krolow** [kombibooth/kombibooth#10]
Create initial page of photo booth label, it should have a link to start take photos it might looks like:

![screenshot from 2015-11-25 21 00 22](https://cloud.githubusercontent.com/assets/46822/11452476/ad927b5c-95cf-11e5-9554-71b7a581410d.png)

**Todo List**
- [x] Create photo booth start page
- [x] Implement layout of photo booth start page
- [x] Turn start page responsive as we dont know what resolution it will run
