### ISSUE TITLE
Format chooser page

### ISSUE THREAD

**Issue by krolow** [kombibooth/kombibooth#3]
It should be possible to user choose one of the output formats available into the app, for that is necessary to create one page where all formats available going to be list, it should be able to preview the results and when user click in such format he will be redirect for the photo viewer page.

The layout will looks similar to:
![screenshot from 2015-11-28 12 43 41](https://cloud.githubusercontent.com/assets/46822/11452407/ac766ac8-95cd-11e5-9fc9-034a4f68bfb5.png)

**Todo list:**
- [ ] Should be able to list format availables
- [ ] Should be able to navigate right, left when there are more formats than we can display in one screen
- [ ] Should be able to preview images in the layout format
