### ISSUE TITLE
Photo viewer page

### ISSUE THREAD

**Issue by krolow** [kombibooth/kombibooth#5]
Should create one page where user can view his photo and choose some photo images filter like: Black and White, Normal, etc...

The page will might looks like:
![screenshot from 2015-11-28 12 47 41](https://cloud.githubusercontent.com/assets/46822/11452425/5da5e260-95ce-11e5-850a-8a16c5f72aac.png)

**Todo List:**
- [ ] Should be able to see photo with the layout choose in previous screen
- [ ] Should be able to change photo filter and see in real time how it will looks like
- [ ] Should be able to confirm and finish the photo take loop
