### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by krolow** [kombibooth/kombibooth#9]
We should create one settings page.

**Todo List:**
- [x] Should be able to decide how many images will be taken
- [x] Should be able to choose folder where should be saved photos
- [x] Should be able to define count down timer of photo take
- [x] Should be able to define how long one image shows after it was taken
